version: 2

build:
  os: ubuntu-22.04 # for Linux compulation
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/source/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub